"""The deterministic half of the claim gate (ARCHITECTURE_PLAN.md §14.3,
§14.1a — goal-scoped M3: the LLM-judge semantic pass stays pluggable and is
not implemented here).

Claim-shaped-string detection over ``headline + caption + image_brief``:

- **Price-shaped strings are always blocked** — F-F's standing
  prices-never-stated policy has no exception, so a price pattern needs no
  ledger lookup at all to fail.
- **Numbers with units/currency/percent** must match a claim in the active
  snapshot by normalized (digits-only) containment — the snapshot's claim
  text is Czech-only (``text_cs``); English copy stating "35,095 answers"
  is checked by comparing the *digit sequence*, not the sentence, which is
  what makes this check language-neutral without needing an English mirror
  of the ledger. ``kvalifikovat`` rows additionally require the
  qualification's own anchor tokens (any year mentioned, plus a
  "reported"/"source-reported" marker) to be present in the checked text.
- **Superlatives and outcome-promise/guarantee language** are blocked
  outright — the shape itself is the defect, not a missing fact.
- **A small deterministic entity/therapeutic-outcome lexicon** blocks
  RAGus-as-current, confidential client names, and the Prohibited-Outcome
  Gate's cheapest layer (a condition/outcome-verb keyword pass, §14.1a).
- **The AI-content disclosure line is required in the caption** (§14.6's
  floor) — a missing disclosure is a defect of the same class as a false
  claim (§14.3: "required-statement is bidirectional").

Verdicts are binary here (``pass`` / ``blocked``) rather than the full
VERIFIED/SAFE-NON-CLAIM/UNSUPPORTED/CONTRADICTED/DISCLOSURE-MISSING
vocabulary — each failing span still names *which* of those reasons fired,
in ``ClaimSpan.kind``, so nothing about the richer vocabulary is lost, it
is just not yet a first-class enum in this goal-scoped pass.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Any

from hypeagent.brand_truth import ClaimEntry, ClaimSnapshot
from hypeagent.config_load import ResolvedList

_PRICE_PATTERNS = [
    re.compile(p, re.IGNORECASE)
    for p in (
        r"\d[\d.,\s]*\s?(kč|czk|eur|eura|euro|usd|\$|€)\b",
        r"[\$€]\s?\d[\d.,]*",
        r"\d[\d.,]*\s?(kč|czk)\b",
        r"/\s?month\b",
        r"\bper\s+month\b",
        r"\bza\s+měsíc\b",
    )
]

# Any grouped-thousands figure ("35,095" / "35.095"), any percentage
# ("25%"), or any bare 3+-digit integer — deliberately unit-agnostic (the
# claim-gate spec calls for "numbers with units/currency/percent", but
# requiring the unit word to sit immediately next to the digits misses
# real phrasing like "35,095 AI responses"; matching the number itself and
# checking it against the snapshot is both simpler and stricter). Standalone
# 1-2 digit numbers ("24/7", "3 steps") are never claim-shaped on their own.
_NUMBER_PATTERN = re.compile(r"\b\d{1,3}(?:[.,]\d{3})+\b|\b\d+(?:\.\d+)?%|\b\d{3,}\b")

_SUPERLATIVE_TERMS = (
    "best", "no. 1", "no.1", "#1", "number one", "top-rated", "top rated",
    "nejlepší", "guaranteed", "guarantee",
)

_OUTCOME_PROMISE_PATTERNS = [
    re.compile(p, re.IGNORECASE)
    for p in (
        r"will\s+double", r"\d+\s?x\s+your", r"zaručeně", r"guarantee(d)?\s+results?",
        r"guaranteed\s+to\b",
    )
]

_DEFAULT_ENTITY_LEXICON = ("ragus", "nuvaro")

_THERAPEUTIC_LEXICON = (
    "cure", "cures", "treat", "treats", "treatment", "heal", "heals", "diagnos",
    "vyléčit", "léčit", "léčba", "uzdravit",
)

_DISCLOSURE_MARKERS = (
    "ai-generated", "ai generated", "generated with ai", "generated by ai",
    "#aigenerated", "vytvořeno pomocí ai", "vygenerováno ai",
)

_DIGITS_RE = re.compile(r"\d+")


@dataclass(frozen=True)
class ClaimSpan:
    kind: str  # price | number | superlative | outcome_promise | entity | therapeutic | disclosure_missing
    field_name: str
    text: str
    reason: str


@dataclass(frozen=True)
class ClaimGateVerdict:
    verdict: str  # pass | blocked
    failing_spans: list[ClaimSpan] = field(default_factory=list)
    checked_fields: tuple[str, ...] = ("headline", "caption", "image_brief")


def _digits_only(text: str) -> str:
    return "".join(_DIGITS_RE.findall(text))


_CLAIM_NUMBER_TOKEN_RE = re.compile(r"\d[\d.,\s]*\d|\d")


def _claim_number_tokens(text: str) -> list[str]:
    """Extract the claim text's own numbers as individual digit tokens
    (not one concatenated blob) — "5 000 Kč ... 35 000 Kč" yields ``["5000",
    "35000"]``, not one merged string, so a short candidate number cannot
    spuriously match by being a substring of an unrelated bigger figure."""
    tokens = []
    for raw in _CLAIM_NUMBER_TOKEN_RE.findall(text):
        digits = _digits_only(raw)
        if digits:
            tokens.append(digits)
    return tokens


def _claim_matches_number(candidate_digits: str, snapshot: ClaimSnapshot) -> ClaimEntry | None:
    """Normalized-containment match, per claim number token: exact equality
    always counts; substring containment (either direction) only counts for
    candidates of 3+ digits, so a short number like "5" cannot spuriously
    match by being a substring of an unrelated bigger ledger figure."""
    for claim in snapshot.claims:
        for token in _claim_number_tokens(claim.text_cs):
            if candidate_digits == token:
                return claim
            if len(candidate_digits) >= 3 and (candidate_digits in token or token in candidate_digits):
                return claim
    return None


def _kvalifikovat_satisfied(text: str, qualification: str) -> bool:
    years = re.findall(r"\b(20\d{2})\b", qualification)
    has_year = all(year in text for year in years) if years else True
    has_reported_marker = bool(re.search(r"report(ed)?|source-reported", text, re.IGNORECASE))
    return has_year and has_reported_marker


def _entity_lexicon(hard_excludes: dict[str, ResolvedList] | None) -> list[str]:
    terms = list(_DEFAULT_ENTITY_LEXICON)
    if hard_excludes:
        do_not_mention = hard_excludes.get("do_not_mention_entities")
        if do_not_mention is not None:
            terms.extend(str(v).lower() for v in do_not_mention.values)
    return terms


def _has_disclosure(caption: str) -> bool:
    lowered = caption.lower()
    return any(marker in lowered for marker in _DISCLOSURE_MARKERS)


def run_claim_gate(
    *,
    headline: str,
    caption: str,
    image_brief: str,
    snapshot: ClaimSnapshot,
    hard_excludes: dict[str, ResolvedList] | None = None,
    slides: list[dict[str, Any]] | None = None,
) -> ClaimGateVerdict:
    """``slides`` (W8-9 Q3b) extends the gated surface to a carousel copy
    asset's per-slide ``title``/``body`` text — the same deterministic
    checks below run over every slide exactly as they run over
    headline/caption/image_brief; a failing span's ``field_name`` names the
    slide index and part (e.g. ``slide_1_title``) so the repair loop can
    point the model at exactly which slide needs a rewrite."""
    fields: dict[str, str] = {"headline": headline or "", "caption": caption or "", "image_brief": image_brief or ""}
    for i, slide in enumerate(slides or [], start=1):
        if not isinstance(slide, dict):
            continue
        fields[f"slide_{i}_title"] = str(slide.get("title") or "")
        fields[f"slide_{i}_body"] = str(slide.get("body") or "")
    spans: list[ClaimSpan] = []
    entity_lexicon = _entity_lexicon(hard_excludes)
    # A kvalifikovat claim's qualification (e.g. a stated period, a
    # "source-reported" framing) may legitimately live in a different field
    # from the number itself — the number in the headline, the period in
    # the caption. The qualification requirement is therefore checked
    # against the asset's full combined text, not one field in isolation.
    combined_text = " ".join(fields.values())

    for field_name, text in fields.items():
        for pattern in _PRICE_PATTERNS:
            m = pattern.search(text)
            if m:
                spans.append(
                    ClaimSpan(
                        kind="price", field_name=field_name, text=m.group(0),
                        reason="price-shaped string always blocked (F-F: prices never stated)",
                    )
                )

        for m in _NUMBER_PATTERN.finditer(text):
            candidate = m.group(0)
            digits = _digits_only(candidate)
            claim = _claim_matches_number(digits, snapshot)
            if claim is None:
                spans.append(
                    ClaimSpan(
                        kind="number", field_name=field_name, text=candidate,
                        reason="unmatched numeric/metric claim — not present in the active claim snapshot",
                    )
                )
                continue
            if claim.behavior == "kvalifikovat" and claim.qualification:
                if not _kvalifikovat_satisfied(combined_text, claim.qualification):
                    spans.append(
                        ClaimSpan(
                            kind="number", field_name=field_name, text=candidate,
                            reason=(
                                f"kvalifikovat claim '{claim.claim_key}' matched but its required "
                                f"qualification is missing from the text: {claim.qualification}"
                            ),
                        )
                    )
            elif claim.behavior == "abstain":
                spans.append(
                    ClaimSpan(
                        kind="number", field_name=field_name, text=candidate,
                        reason=f"claim '{claim.claim_key}' is behavior=abstain — never citable",
                    )
                )

        lowered = text.lower()
        for term in _SUPERLATIVE_TERMS:
            if term in lowered:
                spans.append(
                    ClaimSpan(kind="superlative", field_name=field_name, text=term, reason="superlative/guarantee language blocked outright")
                )
        for pattern in _OUTCOME_PROMISE_PATTERNS:
            m = pattern.search(text)
            if m:
                spans.append(
                    ClaimSpan(kind="outcome_promise", field_name=field_name, text=m.group(0), reason="outcome-promise language blocked outright")
                )
        for entity in entity_lexicon:
            if entity and entity in lowered:
                spans.append(
                    ClaimSpan(kind="entity", field_name=field_name, text=entity, reason="do-not-mention entity present (F-J / F-C negative)")
                )
        for term in _THERAPEUTIC_LEXICON:
            if term in lowered:
                spans.append(
                    ClaimSpan(
                        kind="therapeutic", field_name=field_name, text=term,
                        reason="therapeutic/prohibited-outcome lexicon match (§14.1a Prohibited-Outcome Gate floor)",
                    )
                )

    if not _has_disclosure(caption or ""):
        spans.append(
            ClaimSpan(
                kind="disclosure_missing", field_name="caption", text="",
                reason="caption is missing the required AI-generated-content disclosure line (§14.6)",
            )
        )

    verdict = "blocked" if spans else "pass"
    return ClaimGateVerdict(verdict=verdict, failing_spans=spans)
